name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: tuler/s3-check-action@master
      id: check
      with:
        key: ${{ github.sha }}
      env:
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - run: echo "Do your thing"
      if: steps.check.outputs.exists == 'false'
    
    - name: Create build result
      run: touch $GITHUB_SHA
      if: steps.check.outputs.exists == 'false'

    - name: Copy file to S3
      uses: tpaschalis/s3-cp-action@master
      env:
        FILE: ./${{ github.sha }}
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      if: steps.check.outputs.exists == 'false'
